#!/usr/bin/env python3
"""Emit .graphifyignore for cluster-forge: EAI stack charts, latest version only."""

from __future__ import annotations

from pathlib import Path

ROOT = Path.home() / "eai-build/cluster-forge"

# Charts that matter for the Z13 EAI suite (see scripts/04-platform.sh, 06b-*).
EAI_SOURCES = (
    "amd-gpu-operator",
    "amd-gpu-operator-config",
    "aim-engine",
    "aim-engine-crds",
    "aim-cluster-model-source",
    "airm",
    "aiwb",
    "kaiwo",
    "kaiwo-config",
    "kaiwo-crds",
    "kueue",
    "kueue-config",
    "cert-manager",
    "cert-manager-config",
    "cluster-cert",
    "metallb",
    "envoy-gateway",
    "envoy-gateway-config",
    "kserve",
    "kserve-crds",
    "kuberay-operator",
    "argocd",
    "argocd-config",
    "gitea",
    "gitea-config",
    "keycloak",
    "keycloak-config",
    "eai-infra",
    "cluster-auth",
    "cluster-auth-config",
    "external-secrets",
    "external-secrets-config",
)

TOP_DIRS = ("root", "scripts", "docs")
TOP_FILES = (
    "README.md",
    "PRD.md",
    "EAI_5821_MIGRATION_PLAN.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
)


def latest_version_dir(source_dir: Path) -> Path:
    versions = [p for p in source_dir.iterdir() if p.is_dir()]
    if not versions:
        return source_dir
    return sorted(versions, key=lambda p: p.name)[-1]


def unignore_ancestors(lines: list[str], seen: set[str], rel: str) -> None:
    parts = rel.strip("/").split("/")
    for i in range(len(parts)):
        prefix = "/".join(parts[: i + 1])
        if prefix in seen:
            continue
        seen.add(prefix)
        lines.append(f"!{prefix}/")


def unignore_tree(lines: list[str], seen: set[str], rel: str) -> None:
    unignore_ancestors(lines, seen, rel)
    lines.append(f"!{rel}/**")


def main() -> None:
    lines = [
        "# Generated by scripts/graphify-ignores/gen-cluster-forge-ignore.py",
        "# cluster-forge vendored Helm (~3k files → ~650): EAI charts, latest version only.",
        "# Excludes minio/openbao/otel/kyverno/rabbitmq and nested subcharts.",
        "",
        "*",
    ]
    seen: set[str] = set()
    for name in TOP_FILES:
        if (ROOT / name).is_file():
            lines.append(f"!{name}")
    for d in TOP_DIRS:
        if (ROOT / d).is_dir():
            unignore_tree(lines, seen, d)
    sources = ROOT / "sources"
    if sources.is_dir():
        unignore_ancestors(lines, seen, "sources")
        lines.append("sources/**")
    for name in EAI_SOURCES:
        src = sources / name
        if not src.is_dir():
            continue
        ver = latest_version_dir(src)
        rel = ver.relative_to(ROOT).as_posix()
        unignore_tree(lines, seen, rel)
        for other in src.iterdir():
            if other.is_dir() and other != ver:
                stale = other.relative_to(ROOT).as_posix()
                lines.append(f"{stale}/")
                lines.append(f"{stale}/**")
    lines.extend(
        [
            "",
            "# Noise inside allowed chart trees",
            "**/charts/**",
            "**/ci/**",
            "**/templates/tests/**",
            "graphify-out/**",
            "sbom/**",
        ]
    )
    print("\n".join(lines))


if __name__ == "__main__":
    main()
